### ISSUE TITLE
how to define a  state machine with loop event

### ISSUE THREAD

**Issue by pkvov** [ztellman/automat#17]
(view [1 2 3 4]) get the result
![image](https://cloud.githubusercontent.com/assets/795396/7111957/b81cc320-e1f7-11e4-96e2-cf1557014cb5.png)

how to define a state machine accept  like  123a23a234 as the picture blow
![image](https://cloud.githubusercontent.com/assets/795396/7112006/fe753802-e1f7-11e4-9c77-a7b7f4497f83.png)

**Comment by ztellman** [comment]
```clj
(view [1 2 3 (a/* ['a 2 3]) 4])
```
