### ISSUE TITLE
CompilerException when using aleph and automat together

### ISSUE THREAD

**Issue by aaronbush** [ztellman/automat#19]
I'm trying to use both aleph and automat in a project together.  In `:require`ing libraries from these projects I end up with the error:

`CompilerException java.lang.IllegalAccessError: vector does not exist, compiling:(byte_streams/graph.clj:1:1)`

I've tried to track this down myself and see where byte_streams/graph.clj does the following so that it can refer to clj-tuple's vector.  Beyond that I'm lost.

`(:refer-clojure :exclude [vector type byte-array])`

Here are the dependencies from project.clj:
    `:dependencies [[org.clojure/clojure "1.6.0"]
                           [automat "0.1.3"]
                           [aleph "0.4.0"]])`

Here is the `ns`:
`(ns nettink.core
  (:require
    [automat.core :as a]
    [aleph.tcp :as tcp]))`

Not sure if there is a different way to `:require` these two projects together or not.  Am hoping that you have combined the two before and can help me out.

**Comment by ztellman** [comment]
Can you give me the output of `lein deps :tree`?  I suspect this is because an earlier version of `clj-tuple` called its data structure `tuple`, while now it provides `vector` and `hash-map`.

**Comment by aaronbush** [comment]
Here is the output:

```
Possibly confusing dependencies found:
[automat "0.1.3"] -> [primitive-math "0.1.3"]
 overrides
[aleph "0.4.0"] -> [byte-streams "0.2.0"] -> [primitive-math "0.1.4"]

Consider using these exclusions:
[aleph "0.4.0" :exclusions [primitive-math]]

[automat "0.1.3"] -> [potemkin "0.3.4"]
 overrides
[aleph "0.4.0"] -> [potemkin "0.3.13"]

Consider using these exclusions:
[aleph "0.4.0" :exclusions [potemkin]]

[automat "0.1.3"] -> [riddley "0.1.7"]
 overrides
[aleph "0.4.0"] -> [byte-streams "0.2.0"] -> [manifold "0.1.0"] -> [riddley "0.1.9"]
 and
[aleph "0.4.0"] -> [manifold "0.1.0"] -> [riddley "0.1.9"]

Consider using these exclusions:
[aleph "0.4.0" :exclusions [riddley]]
[aleph "0.4.0" :exclusions [riddley]]

[automat "0.1.3"] -> [potemkin "0.3.4"] -> [clj-tuple "0.1.2"]
 overrides
[aleph "0.4.0"] -> [potemkin "0.3.13"] -> [clj-tuple "0.2.1"]
 and
[aleph "0.4.0"] -> [byte-streams "0.2.0"] -> [clj-tuple "0.2.1"]

Consider using these exclusions:
[aleph "0.4.0" :exclusions [clj-tuple]]
[aleph "0.4.0" :exclusions [clj-tuple]]

warn
 [aleph "0.4.0"]
   [byte-streams "0.2.0"]
   [io.aleph/dirigiste "0.1.0"]
   [io.netty/netty-all "4.1.0.Beta4"]
   [manifold "0.1.0"]
   [org.clojure/tools.logging "0.3.1"]
 [automat "0.1.3"]
   [potemkin "0.3.4"]
     [clj-tuple "0.1.2"]
   [primitive-math "0.1.3"]
   [proteus "0.1.4"]
   [rhizome "0.2.1"]
   [riddley "0.1.7"]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.6.0"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]
```

I switched the order of the dependencies to have aleph before automat and that cleared most of the above warnings and resolved the issue with vector not being found.

**Comment by ztellman** [comment]
Please add `[clj-tuple "0.2.2"]` to your dependencies, which should fix the issue.
