### ISSUE TITLE
Documentation link incomplete

### ISSUE THREAD

**Issue by Engelberg** [ztellman/automat#21]
The README says to go to `http://ideolalia.com/automat/` for the complete documentation, but that link only contains the docs for the viz namespace.

**Comment by ztellman** [comment]
This appears to be some sort of cljx issue, I regenerated the documentation from pre-cljx days and pushed it.  Thanks for the report!

**Comment by Engelberg** [comment]
FYI, I'm still only seeing the viz namespace docs at http://ideolalia.com/automat/
