### ISSUE TITLE
 No such var: automat.core/range

### ISSUE THREAD

**Issue by dsapoetra** [ztellman/automat#22]
Hi there! Sorry to disturb you.
I try to use your library today, and when i tested it with example from README.md , i get error when i use automat.core/range, i put the screenshot of the error : 
<img width="554" alt="screen shot 2015-08-26 at 11 45 22 am" src="https://cloud.githubusercontent.com/assets/3592714/9485737/25cb961c-4be8-11e5-9fbd-aae2899bd991.png">

i use this version : [automat "0.1.3"]

Thank you!

**Comment by ztellman** [comment]
Hi, the README describes a function in the upcoming 0.2.0 release, not the 0.1.3 release.  Try `..` instead of `range`.

**Comment by dsapoetra** [comment]
Thank you! I'm sorry because the README still writes 0.1.3 version.

**Comment by ztellman** [comment]
No, that's my fault.  I'm going to update the README to give the correct value for 0.1.3
