### ISSUE TITLE
docs are nearly empty?

### ISSUE THREAD

**Issue by timvisher** [ztellman/automat#25]
The linked docs are nearly empty and only provide the latest snapshot rather than 0.1.3. http://ideolalia.com/automat

**Comment by achengs** [comment]
Update: It now says "no such thing"

**Comment by osfameron** [comment]
It looks like the link is now pointing to http://aleph.io/codox/automat/ for Automat 0.2.0.  These docs are still rather sketchy (in terms of e.g. the inputs and outputs of the functions) but I think the original issue is fixed!
