### ISSUE TITLE
$ only accepts keyword states, it would be nice if that was not the case

### ISSUE THREAD

**Issue by hiredman** [ztellman/automat#28]
the $ function has a precondition of `keyword?`, and that limits reduction operations to fsm with alphabets that are keywords.

**Comment by DomKM** [comment]
The argument to `$` is not an input, it is a tag for an action. You use this tag as a key in a map of reducer functions passed to `compile`. An FSM like `[1 (a/$ :begin) 2 3 4 (a/$ :end)]`, where the alphabet does not include keywords, works fine.

**Comment by hiredman** [comment]
oh, thanks, suddenly the diagrams with the tag make a lot more sense
