### ISSUE TITLE
timeout example

### ISSUE THREAD

**Issue by coreasync** [ztellman/automat#36]
While I think I know how I would do that (via reducer functions), I am looking for a recommendation how to achieve timeout transitions.

**Comment by coreasync** [comment]
optimally, timeout supports would be in the library though

**Comment by ztellman** [comment]
The automata advancement doesn't block, I'm not sure how a timeout would fit into the library.  Typically a timeout would be a signal, which may or may not be a valid signal depending on whether the event has already occurred.

**Comment by coreasync** [comment]
I realize that an automata advancement does not block, and of course timers out be managed outside of the library. However, in my case, I deal with different timeouts for different states and have a need to somehow create those timers, e.g. using `overtone/at-at` and manage them depending on states. For instance, in case the timer does not trigger, I need to be able to cancel it. In other case/state I might need to set two timers causing different signals. In another words, I need to tell what state I am in, and in that sense I would need a support from the library. I initially though to use reducer functions, but now see it will not work.

**Comment by ztellman** [comment]
Closing, as this is out of scope for this library.
