### ISSUE TITLE
different reducers for self-transitions

### ISSUE THREAD

**Issue by coreasync** [ztellman/automat#38]
I would like ask for an example (not sure how to achieve it) how to define automata and have following reducers attached:

![image](https://cloud.githubusercontent.com/assets/6901155/14448678/a895750e-001f-11e6-9cdf-2ccb05b0ba4e.png)

Thank you

**Comment by ztellman** [comment]
Sorry, I'm not sure what you're asking here.  Can you elaborate?

**Comment by coreasync** [comment]
That was my attempt to create a self-transition for timeout case. However, it was a result partially ill-thinking of mine as well as confusion from `README.md` where `(fn [state input] _)` in an example reducer suggested that we know the state. But it is more like `(fn [value input] _)`.
