### ISSUE TITLE
Compilation error in Clojure 1.8?

### ISSUE THREAD

**Issue by fasiha** [ztellman/automat#39]
`[automat "0.1.3"]` in `project.clj`'s `dependencies`. When I `lein repl` and try to require `view`, I see:

```
user=> (require '[automat.viz :refer (view)])

CompilerException java.lang.NoClassDefFoundError: IllegalName: compile__stub.automat.fsm.automat.fsm/State, compiling:(automat/fsm.clj:18:1)
```

Really sorry if this is a known problem, I tried googling and poking around github, but can't find anything, and am super-excited to try it!

**Comment by huahaiy** [comment]
Try this: https://github.com/ztellman/automat/pull/35
It seems to work

**Comment by vitalyper** [comment]
As @huahaiy suggested automat was ported to support clojure 1.7 and 1.8. 

Please use below in your **project.clj**

[org.clojars.semperos/automat "0.2.0-alpha3"]
