### ISSUE TITLE
Customize viz (edge) labels

### ISSUE THREAD

**Issue by cemerick** [ztellman/automat#47]
I'm generating FSMs that use integers as inputs/signals, but they're actually character codes. (Doing this so `range` and such are available.) I'd like to get characters on the visualizations' edges, but I don't see an easy way to do so. Looks like I could do unwise things to `#'pprint-inputs` as a workaround, but maybe I'm missing something more straightforward?

**Comment by ztellman** [comment]
There's not really an easy way to do this right now.  Unwise things with `pprint-inputs` may be the easiest thing, or you can just copy/paste/adapt the rest of the code to your needs (there's not that much).

**Comment by cemerick** [comment]
`pprint-inputs` was enough, thanks. :-)

Feel free to close this if you don't want it clogging up your issue tracker.
