### ISSUE TITLE
WARNING: cljs.core/bit-or

### ISSUE THREAD

**Issue by zalky** [ztellman/automat#60]
Seeing a warning in cljs:

```clj
WARNING: cljs.core/bit-or, all arguments must be numbers, got [clj-nil number] inste
ad. at line 601 /Users/zalan/.boot/cache/tmp/Users/zalan/src/semion/onty/2ao/-bj0ipr
/main.out/automat/fsm.cljc                                                         
```

Simple test case:

```clj
(ns simple.core
  (:require [automat.core :as a]))

(a/compile [1])
```
Tested with:

- boot: 2.5.5
- clojure: 1.8.0
- cljs: 1.8.40, 1.9.76,  1.9.225

It doesn't seem to have any affect in my simple use cases. Is this a known issue? Is this something to worry about?

**Comment by ztellman** [comment]
I'm also seeing this error, but `bit-or` isn't used anywhere in the library, so I think it's something else that's causing it.
