### ISSUE TITLE
Using AOT with clojurescript dependency throws ClassCastException

### ISSUE THREAD

**Issue by tangrammer** [ztellman/automat#68]
Hi @ztellman just updating this problem in a clean and separate issue 

### Description 
+ adding `org.clojure/clojurescript` dependency and `:aot :all` with `ztellman/automat` throws error when executing standalone jar
` Caused by: java.lang.ClassCastException: clojure.lang.Var$Unbound cannot be cast to clojure.lang.MultiFn`

### example code
https://github.com/tangrammer/automat-issue

**Comment by tangrammer** [comment]
I've checked that the problem arises when a namespace that contains references to automat classes is included in AOT directly or indirectly ...
Please, could anyone point me where the root of this issue lives so i could ask in the proper place?
thanks in advance

**Comment by cemerick** [comment]
I have the same problem. Investigating now. @tangrammer if you have any further information since your last post, please let us know. 😄

**Comment by ztellman** [comment]
I'm sorry that I can't be much help here, the whole CLJS ecosystem is a bit of a mystery to me.  I'll call @DomKM to this thread, though, since he's to blame for the CLJS portion of this library.

**Comment by cemerick** [comment]
The result of my proposed fix #69 is available here, if anyone wants to test it themselves in an AOT project that also uses CLJS:

`[org.clojars.cemerick/automat "0.2.3-SNAPSHOT"]`

**Comment by tangrammer** [comment]
Hi @cemerick sorry but I don't have more information around this issue. 
Hope you have more tools to try to fix it!
