### ISSUE TITLE
svg viewing problem

### ISSUE THREAD

**Issue by naipmoro** [ztellman/automat#7]
When the result of automat's fsm->dot is run through rhizome's dot->svg, the resulting
svg fragment doesn't display the entire automata. Specifically, the svg's width and height
are larger than the viewBox dimensions:
```clj
(-> (automat/fsm->dot [1] {}) rhizome/dot->svg)
;=>  ... <svg width="242pt" height="72pt"  viewBox="0.00 0.00 174.00 52.00" ...
```
I need to call {:dpi 72} to get a correct rendering. I'm on ubuntu 12.04.
```clj
(-> (automat/fsm->dot [1] {:dpi 72}) rhizome/dot->svg)
;=>  ... <svg width="174pt" height="52pt"  viewBox="0.00 0.00 174.00 52.00" ...
```
I'm using the svg fragments to render the automata in gorilla-repl.

**Comment by ztellman** [comment]
I'm sorry that I somehow overlooked this for so long.  I'm just using the svg rendering functionality in `dot`, so I don't have a lot of control over it.  Out of curiosity (assuming you're still around), what version of graphviz are you using?

**Comment by naipmoro** [comment]
Hi! Thanks for replying. I'm using graphviz version 2.26.3, which is the most recent one provided by ubuntu 12.04's package manager.
